# Generated by Django 3.2.13 on 2024-09-08 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemename', models.CharField(max_length=255)),
                ('ministry', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('place', models.CharField(max_length=255)),
                ('moneygranted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneyspent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=100)),
                ('progress', models.FloatField()),
                ('timeOfschemeAdded', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('srno', models.PositiveIntegerField()),
                ('lasteditedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_schemes', to=settings.AUTH_USER_MODEL)),
                ('leadperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_person_schemes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
    ]
